#!/bin/sh /etc/rc.common

START=97
STOP=10
USE_PROCD=1
PROCD_DEBUG=1

start_service() {
	/usr/bin/mem 0x10000060 0x5015400E
	cd /sys/class/gpio
	echo 37 > export
	echo 38 > export
	echo 39 > export
	echo 40 > export
	echo 41 > export
	echo 42 > export
	echo 43 > export
	for x in gpio[0-9]*; do
		cd $x
		echo out > direction
		cd ..
	done

	procd_open_service "blink"
	procd_open_instance
	procd_set_param command /etc/blink.sh

	# respawn automatically if something died, be careful if you have an alternative process supervisor
	# if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

	procd_close_instance
	procd_close_service
}
